# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-08 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccount', models.IntegerField(verbose_name='数量')),
            ],
            options={
                'verbose_name': '购物车',
                'db_table': 'CartInfo',
                'verbose_name_plural': '购物车',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='商品名称')),
                ('picture', models.ImageField(null=True, upload_to='static/upload/goods', verbose_name='商品图片')),
                ('spec', models.CharField(max_length=30, verbose_name='商品规格')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='商品价格')),
                ('isActive', models.BooleanField(default=True, verbose_name='是否上架')),
            ],
            options={
                'verbose_name': '商品',
                'db_table': 'Goods',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='类型名称')),
                ('picture', models.ImageField(null=True, upload_to='static/upload/goodstype', verbose_name='类型图片')),
                ('desc', models.TextField(verbose_name='商品描述')),
            ],
            options={
                'verbose_name': '商品类型',
                'db_table': 'GoodsType',
                'verbose_name_plural': '商品类型',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uphone', models.CharField(max_length=20, verbose_name='定哇号码')),
                ('upwd', models.CharField(max_length=20, verbose_name='密码')),
                ('uemail', models.EmailField(max_length=254, verbose_name='优箱')),
                ('uname', models.CharField(max_length=20, verbose_name='名字')),
                ('isActive', models.BooleanField(verbose_name='是否激活')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='goodsType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.GoodsType', verbose_name='商品类型'),
        ),
        migrations.AddField(
            model_name='cartinfo',
            name='goods_id',
            field=models.ForeignKey(db_column='good_id', on_delete=django.db.models.deletion.CASCADE, to='index.Goods', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='cartinfo',
            name='users_id',
            field=models.ForeignKey(db_column='users_id', on_delete=django.db.models.deletion.CASCADE, to='index.Users', verbose_name='用户'),
        ),
    ]
